language: node_js
node_js:
  - 12

services: 
  - docker

# pre-testing installs
install: 
  - echo "nothing needs to be installed"

before_script:
  - echo "no tests"

script:
  - docker --version
  - docker build -t udagram-frontend .
  - docker tag udagram-frontend yahyabadawy/udagram-frontend:latest

# Tasks to perform after the process is successful.
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push yahyabadawy/udagram-frontend